# Generated by Django 4.2.25 on 2026-09-07 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_codigospostalesmx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.BigIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "cheque_devuelto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
                ),
                ("clave", models.CharField(max_length=255)),
                ("foliorfc", models.BigIntegerField(default=1)),
                ("forma_de_pago", models.BigIntegerField(default=1)),
                ("juridico", models.BooleanField(default=False)),
                ("nombre", models.CharField(max_length=255)),
                ("permite_cheque", models.BooleanField(default=False)),
                ("rfc", models.CharField(max_length=13)),
                ("sw2", models.BigIntegerField(blank=True, null=True)),
                ("uso_cfdi", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "direccion_calle",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "direccion_codigo_postal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "direccion_colonia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "direccion_estado",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "direccion_latitud",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "direccion_longitud",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "direccion_municipio",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "direccion_numero_exterior",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "direccion_numero_interior",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "direccion_pais",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "create_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "update_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "razon_social",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "regimen_fiscal",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={"db_table": "cliente", "managed": False,},
        ),
    ]
