# Generated by Django 3.2 on 2025-01-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion_gps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
