# Generated by Django 3.2 on 2023-08-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sx_instruccion_de_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('almacen', models.CharField(blank=True, max_length=255, null=True)),
                ('operador', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField()),
                ('instruccion_de_entrega_parcial', models.CharField(blank=True, max_length=255, null=True)),
                ('clave', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=19)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('create_user', models.CharField(blank=True, max_length=255, null=True)),
                ('update_user', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.BigIntegerField()),
                ('parcial', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'entrega_parcial',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EntregaParcial',
        ),
    ]
