# Generated by Django 3.2 on 2024-11-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0002_auto_20241120_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviodet',
            name='kxmil',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='enviodet',
            name='me_bienes_transp',
            field=models.CharField(blank=True, default='sin variable', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enviodet',
            name='me_clave_unidad',
            field=models.CharField(blank=True, default='no info', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enviodet',
            name='me_material_peligroso',
            field=models.CharField(blank=True, default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='enviodet',
            name='cortes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
