# Generated by Django 3.2 on 2023-08-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0002_auto_20230829_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaDet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sx_instruccion_de_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('almacen', models.CharField(blank=True, max_length=255, null=True)),
                ('instruccion_de_entrega_parcial', models.CharField(blank=True, max_length=255, null=True)),
                ('clave', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=19)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('create_user', models.CharField(blank=True, max_length=255, null=True)),
                ('update_user', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.BigIntegerField()),
            ],
            options={
                'db_table': 'entrega_det',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EntregaRecorrido',
        ),
        migrations.AlterModelTable(
            name='entrega',
            table='entrega',
        ),
    ]
