# Generated by Django 3.2 on 2023-08-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0003_auto_20230831_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(blank=True, max_length=255, null=True)),
                ('folio', models.BigIntegerField()),
                ('serie', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'folio',
                'managed': True,
            },
        ),
    ]
