# Generated by Django 3.2 on 2024-11-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0003_auto_20241120_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrucciondeenvio',
            name='clasificcion_vale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instrucciondeenvio',
            name='email_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instrucciondeenvio',
            name='origen_sx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instrucciondeenvio',
            name='tipo_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enviodet',
            name='cortes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='instrucciondeenvio',
            name='version',
            field=models.BigIntegerField(default=0),
        ),
    ]
