# Generated by Django 3.2 on 2024-11-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0004_auto_20241120_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrucciondeenvio',
            name='sx_transporte',
            field=models.ForeignKey(blank=True, db_column='sx_transporte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transporte_foraneo', to='embarques.transporteforaneo', to_field='sx'),
        ),
    ]
