# Generated by Django 3.2 on 2023-08-31 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0004_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='embarques.sucursal'),
        ),
        migrations.AddField(
            model_name='folio',
            name='sucursal_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
