# Generated by Django 3.2 on 2024-11-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0005_alter_instrucciondeenvio_sx_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='recepcion_longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=19, null=True),
        ),
    ]
