# Generated by Django 3.2 on 2024-02-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0005_auto_20230831_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operador',
            options={'managed': True},
        ),
    ]
