# Generated by Django 3.2 on 2024-11-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0006_alter_entrega_recepcion_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='maniobra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.CreateModel(
            name='EnvioAnotaciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('anotacion', models.CharField(max_length=600)),
                ('revisada', models.BooleanField(default=False)),
                ('create_user', models.CharField(blank=True, max_length=255, null=True)),
                ('update_user', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anotaciones', to='embarques.envio')),
            ],
            options={
                'db_table': 'envio_anotaciones',
                'managed': True,
            },
        ),
    ]
