# Generated by Django 3.2 on 2024-02-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0007_auto_20240208_1209'),
    ]

    operations = [

    ]
