# Generated by Django 3.2 on 2024-12-02 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0007_auto_20241127_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=255)),
                ('principal', models.BooleanField(default=False)),
                ('destinatario', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('numero_exterior', models.CharField(max_length=255)),
                ('numero_interior', models.CharField(blank=True, max_length=255, null=True)),
                ('colonia', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=19)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=19)),
                ('version', models.BigIntegerField()),
                ('create_user', models.CharField(blank=True, max_length=255, null=True)),
                ('update_user', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'direccion_entrega',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreEntrega',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sucursal', models.CharField(max_length=255)),
                ('destinatario', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.CharField(max_length=255)),
                ('fecha_documento', models.DateTimeField()),
                ('surtido', models.DateTimeField(blank=True, null=True)),
                ('enviado', models.DateTimeField(blank=True, null=True)),
                ('surtidor', models.CharField(blank=True, max_length=255, null=True)),
                ('create_user', models.CharField(blank=True, max_length=255, null=True)),
                ('update_user', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('direccion_entrega', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preentregas', to='embarques.direccionentrega')),
            ],
            options={
                'db_table': 'pre_entrega',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='surtido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='surtidor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enviodet',
            name='surtido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviodet',
            name='surtidor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PreEntregaDet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('cortes', models.CharField(blank=True, max_length=255, null=True)),
                ('clave', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('surtido', models.DateTimeField(blank=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=255, null=True)),
                ('update_user', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('envio_det', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preentregas', to='embarques.enviodet')),
                ('preentrega', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='embarques.preentrega')),
            ],
            options={
                'db_table': 'pre_entrega_det',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='preentrega',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preentregas', to='embarques.envio'),
        ),
    ]
