# Generated by Django 3.2 on 2024-02-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0008_auto_20240209_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='facturista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='embarques.facturistaembarques'),
        ),
        migrations.AddField(
            model_name='operador',
            name='transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='embarques.transporteembarques'),
        ),
    ]
