# Generated by Django 3.2 on 2024-12-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0009_preentrega_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='preentrega',
            name='folio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preentrega',
            name='comentario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preentrega',
            name='direccion_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='embarques.direccionentrega'),
        ),
    ]
