# Generated by Django 3.2 on 2024-03-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0009_auto_20240220_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgEntrega',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url_image', models.CharField(max_length=255)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='embarques.entrega')),
            ],
            options={
                'db_table': 'img_entrega',
                'managed': True,
            },
        ),
    ]
