# Generated by Django 3.2 on 2024-12-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0010_auto_20241202_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='preentrega',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
