# Generated by Django 3.2 on 2024-03-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0010_imgentrega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregaincidencia',
            options={'managed': True},
        ),
    ]
