# Generated by Django 3.2 on 2024-12-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0011_preentrega_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionentrega',
            name='version',
            field=models.BigIntegerField(default=0),
        ),
    ]
