# Generated by Django 3.2 on 2024-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0012_auto_20240312_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaincidencia',
            name='create_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entregaincidencia',
            name='update_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
