# Generated by Django 3.2 on 2024-12-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0012_alter_direccionentrega_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='preentrega',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
