# Generated by Django 3.2 on 2024-12-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0013_preentrega_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preentrega',
            name='surtidor',
        ),
        migrations.AddField(
            model_name='preentregadet',
            name='surtidor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
