# Generated by Django 3.2 on 2024-12-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0014_auto_20241203_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='surtidor',
        ),
    ]
