# Generated by Django 3.2 on 2024-03-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0015_entregaincidencia_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaincidencia',
            name='destinatario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entregaincidencia',
            name='documento',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entregaincidencia',
            name='entidad',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entregaincidencia',
            name='fecha_documento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entregaincidencia',
            name='operador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entregaincidencia',
            name='origen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entregaincidencia',
            name='realizo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entregaincidencia',
            name='sucursal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entregaincidencia',
            name='tipo_documento',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
