# Generated by Django 3.2 on 2024-12-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0017_preentrega_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
