# Generated by Django 3.2 on 2024-03-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0017_entregaincidencia_embarque'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaIncidenciaSeguimiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('create_user', models.CharField(blank=True, max_length=255, null=True)),
                ('update_user', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='embarques.entregaincidencia')),
            ],
            options={
                'db_table': 'entrega_incidencia_seguimiento',
                'managed': True,
            },
        ),
    ]
