# Generated by Django 3.2 on 2025-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0018_envio_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteembarques',
            name='imei',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
