# Generated by Django 3.2 on 2024-04-04 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0019_entregaincidencia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaincidenciaseguimiento',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seguimientos', to='embarques.entregaincidencia'),
        ),
    ]
