# Generated by Django 3.2 on 2025-01-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0020_transporteembarques_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteembarques',
            name='capacidad_kilos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='transporteembarques',
            name='capacidad_max_kilos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='transporteembarques',
            name='capacidad_max_volumen',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='transporteembarques',
            name='capacidad_volumen',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
    ]
