# Generated by Django 3.2 on 2025-02-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0021_auto_20250127_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionentrega',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
