# Generated by Django 3.2 on 2025-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0022_alter_direccionentrega_numero_exterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='folio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
