# Generated by Django 4.2.25 on 2026-07-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embarques", "0023_envio_folio"),
    ]

    operations = [
        migrations.AddField(
            model_name="direccionentrega",
            name="contacto",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="direccionentrega",
            name="horario_recepcion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="direccionentrega",
            name="horario_recepcion_fin",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="direccionentrega",
            name="horario_recepcion_inicio",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="direccionentrega",
            name="telefono_contacto",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
