# Generated by Django 3.2 on 2024-08-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0023_alter_entregaincidenciaseguimiento_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'managed': False, 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
    ]
