# Generated by Django 3.2 on 2024-10-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0024_alter_sucursal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeolocalizacionTransportes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=19)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=19)),
                ('distancia', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('version', models.BigIntegerField(default=0)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='embarques.sucursal')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='embarques.transporteembarques')),
            ],
            options={
                'db_table': 'geolocalizacion_transportes',
                'managed': True,
            },
        ),
    ]
