# Generated by Django 4.2.25 on 2026-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embarques", "0024_direccionentrega_contacto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="envio",
            name="sucursal_entrega",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
