# Generated by Django 4.2.25 on 2026-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embarques", "0025_envio_sucursal_entrega"),
    ]

    operations = [
        migrations.AddField(
            model_name="direccionentrega",
            name="horario_recepcion_fin2",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="direccionentrega",
            name="horario_recepcion_inicio2",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
