# Generated by Django 3.2 on 2024-10-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0025_geolocalizaciontransportes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocalizaciontransportes',
            options={'managed': False},
        ),
    ]
