# Generated by Django 3.2 on 2024-10-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0026_alter_geolocalizaciontransportes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocalizaciontransportes',
            options={'managed': True},
        ),
    ]
