# Generated by Django 4.2.25 on 2026-08-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embarques", "0026_direccionentrega_horario_recepcion_fin2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="direccionentrega",
            name="atiende_sabado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="direccionentrega",
            name="horario_sabado_fin",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="direccionentrega",
            name="horario_sabado_inicio",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
