# Generated by Django 3.2 on 2024-10-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0027_alter_geolocalizaciontransportes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocalizaciontransportes',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ubicaciones', to='embarques.transporteforaneo'),
        ),
    ]
