# Generated by Django 4.2.25 on 2026-09-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("embarques", "0028_envio_origen_enviodet_activo"),
    ]

    operations = [
        migrations.RemoveField(model_name="direccionentrega", name="atiende_sabado",),
        migrations.RemoveField(
            model_name="direccionentrega", name="horario_sabado_fin",
        ),
        migrations.RemoveField(
            model_name="direccionentrega", name="horario_sabado_inicio",
        ),
    ]
