# Generated by Django 3.2 on 2024-02-08 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=False)),
                ('clave', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion_calle', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion_numero_exterior', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_numero_interior', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_codigo_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_colonia', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_estado', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_pais', models.CharField(blank=True, max_length=100, null=True)),
                ('almacen', models.BooleanField(default=False)),
                ('db_url', models.CharField(blank=True, max_length=255, null=True)),
                ('sx', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('create_user', models.CharField(blank=True, max_length=100, null=True)),
                ('update_user', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.BigIntegerField()),
                ('or_municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('or_estado', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=19, null=True)),
                ('direccion_longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.sucursal'),
        ),
    ]
